181-Getting patient with the health Id
Bahmni-Covid19/openmrs-module-hip pull request #20
Opened 2021-05-20 04:43 UTC by Mahesh-I

2021-05-20 04:59 UTC, Nazeer-debug approved these changes

2021-05-20 05:20 UTC, swatigogia2020 approved these changes

2021-05-24 10:47 UTC, merged

2021-05-24 10:48 UTC, swatigogia2020 requested changes

2021-05-24 10:48 UTC, swatigogia2020 commented on api/src/main/java/org/bahmni/module/hip/api/dao/impl/ExistingPatientDaoImpl.java
> +    public static final int HEALTH_ID_IDENTIFIER_TYPE_ID = 5;
why is this hardcoded