230|[Tazeen|Nazeer]|Adds returning phone number in existing patient A…
Bahmni-Covid19/openmrs-module-hip pull request #27
Opened 2021-06-08 09:25 UTC by Nazeer-debug

…PI response

2021-06-08 12:08 UTC, swatigogia2020 requested changes

2021-06-08 12:08 UTC, swatigogia2020 commented on api/src/main/java/org/bahmni/module/hip/api/dao/impl/ExistingPatientDaoImpl.java
> +    private static final int PERSON_PHONE_NUMBER_ATTRIBUTE_TYPE_ID = 15;
refrain hard coded value, use attribute name

2021-06-09 04:38 UTC, MeghnaThoughtworks approved these changes

2021-06-09 04:38 UTC, MeghnaThoughtworks commented on api/src/main/java/org/bahmni/module/hip/api/dao/impl/ExistingPatientDaoImpl.java
> +    private static final int PERSON_PHONE_NUMBER_ATTRIBUTE_TYPE_ID = 15;
+1

2021-06-09 09:31 UTC, Mahesh-I approved these changes

2021-06-09 09:31 UTC, Mahesh-I commented on api/src/main/java/org/bahmni/module/hip/api/dao/ExistingPatientDao.java
> +    }
fix the alignment and remove unnecessary extra lines

2021-06-16 09:24 UTC, merged