125 op consult
Bahmni-Covid19/openmrs-module-hip pull request #33
Opened 2021-07-28 11:43 UTC by Mahesh-I

2021-07-29 06:29 UTC, swatigogia2020 requested changes

2021-08-03 05:12 UTC, swatigogia2020 requested changes
Make sure to use concept names( etc) to be names instead of id's and make them constants.
Apart from it, everything looks fine

2021-08-03 05:12 UTC, swatigogia2020 commented on api/src/main/java/org/bahmni/module/hip/api/dao/impl/OPConsultDaoImpl.java
> +                "\t\tand o2.concept_id = 156 group by o2.obs_group_id) and o1.value_coded is not null ;";
instead of concept_id=156, use concept name and make it a constant

2021-08-03 05:12 UTC, swatigogia2020 commented on api/src/main/java/org/bahmni/module/hip/api/dao/impl/OPConsultDaoImpl.java
> +        final int diagnosisValueConceptId = 15;
use concept name

2021-08-23 07:47 UTC, swatigogia2020 approved these changes

2021-08-24 05:48 UTC, Nazeer-debug requested changes

2021-08-24 05:48 UTC, Nazeer-debug commented on omod/src/test/java/org/bahmni/module/hip/web/TestConfiguration.java
> +import org.bahmni.module.hip.web.service.*;
don't use * imports

2021-08-24 05:48 UTC, Nazeer-debug commented on omod/src/main/java/org/bahmni/module/hip/web/service/OPConsultService.java
> +import org.bahmni.module.hip.web.model.*;
*  imports in the class
*

2021-08-24 05:48 UTC, Nazeer-debug commented on pom.xml
> +<!--			</dependency>-->
remove it, if you are not using it

2021-08-24 05:48 UTC, Nazeer-debug commented on omod/src/main/java/org/bahmni/module/hip/web/model/FhirOPConsult.java
> +import java.util.*;
* imports

2021-08-24 07:14 UTC, rohit-yawalkar commented on omod/src/test/java/org/bahmni/module/hip/web/TestConfiguration.java
> +import org.bahmni.module.hip.web.service.*;
@Nazeer-debug we removed * imports.

2021-08-24 07:14 UTC, rohit-yawalkar commented on pom.xml
> +<!--			</dependency>-->
@Nazeer-debug we removed this comment

2021-08-24 08:54 UTC, Nazeer-debug approved these changes

2021-08-24 09:02 UTC, merged